# Author guomin
name="my naMe is maguomin"
print(name.lower())
print(name.upper())
print(name.endswith('in'))
print(name.startswith('mya'))
print(name[name.find("name"):])
print('123'.isalnum())
print('dfdf'.isalpha())
print('1.33'.isdecimal())
print('|'.isidentifier())
print('333'.isnumeric())
print('My Name'.istitle())
print('My Name'.isupper())
print(','.join(['a','b','c']))
print(name.ljust(50,'*'))
print(name.rjust(50,'*'))
print('    test     '.strip())
print('alex li'.replace('l','L',1))
print('alex lil'.rfind('l'))
print('1+2+3+4+5'.split('+'))
print('lex li'.zfill(20))